core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('homepage.urls')),
    path('', include('tenants.urls')),
    path('', include('boardinghouse.urls')),
    path('', include('payments.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path

from payments import views

urlpatterns = [
    path('utility-bill/', views.utility_bill, name='utility-bill'),
    path('payments/', views.payments, name='payments'),
    path('payments/<int:id>/', views.payments_info, name='payments-info'),
    path('payments/transient/', views.transient, name='transient'),
    path('payments/transient/<int:id>/', views.transient_info, name='transient-info'),
    path('income/', views.income, name='income'),
    path('collectibles/', views.collectibles, name='collectibles'),
    ]

payments/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from tenants.models import Tenant


class Bills(models.Model):
    room = models.ForeignKey('boardinghouse.Room', on_delete = models.CASCADE)
    bills = models.CharField(max_length=100)
    rate = models.CharField(max_length=100)

    def __str__(self):
        return self.bills


class Payments(models.Model):
    room = models.ForeignKey('boardinghouse.Room', on_delete=models.CASCADE)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    amount = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    note = models.CharField(max_length=100, blank=True, null=True)
    mode = models.CharField(max_length=100, blank=True, null=True)


    def __str__(self):
        return self.amount

    def save(self, *args, **kwargs):
        tenant = Tenant.objects.get(id=self.tenant.id)
        tenant.amount_paid = float(tenant.amount_paid) + float(self.amount)
        tenant.save()
        super(Payments, self).save(*args, **kwargs)


class TransientPayment(models.Model):
    room = models.ForeignKey('boardinghouse.Room', on_delete=models.CASCADE)
    transient = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    days = models.IntegerField(default=0)
    amount = models.CharField(max_length=100)
    note = models.CharField(max_length=100, blank=True, null=True)
    mode = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField(auto_now_add=True)

payments/forms.py
from django import forms

from payments.models import Bills, Payments, TransientPayment

BILL_CHOICES =(
        ('Electricity', 'Electricity'),
        ('Water', 'Water'),
        ('Internet', 'Internet'),
        ('Cable', 'Cables'),
        ('Others', 'Others')
    )
class BillsForm(forms.ModelForm):


    class Meta:
        model = Bills
        fields = [ 'bills', 'rate']
        widgets = {

            'bills': forms.Select(choices=BILL_CHOICES , attrs={'class': 'form-control'}),
            'rate': forms.TextInput(attrs={'class': 'form-control'}),
        }

class PaymentsForm(forms.ModelForm):
    class Meta:
        model = Payments
        fields = ['amount', 'note', 'mode']
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'note': forms.TextInput(attrs={'class': 'form-control'}),
            'mode': forms.TextInput(attrs={'class': 'form-control'}),
        }

class TransientPaymentForm(forms.ModelForm):
    class Meta:
        model = TransientPayment
        fields = ['room', 'transient', 'address', 'contact', 'days', 'amount', 'note', 'mode']
        widgets = {
            'room': forms.Select(attrs={'class': 'form-control', 'required': True}),
            'transient': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'contact': forms.TextInput(attrs={'class': 'form-control', 'required': True, 'pattern': "(^\+639\d{9}$)|(^\d{11}$)" , 'title': "Please enter a valid Philippine contact number in the format: +639123456789 or 09123456789"}),
            'days': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'note': forms.TextInput(attrs={'class': 'form-control'}),
            'mode': forms.TextInput(attrs={'class': 'form-control'}),
        }

payments/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect

from boardinghouse.models import Room
from homepage.models import Feedback, Notice
from payments.forms import BillsForm, PaymentsForm, TransientPaymentForm
from payments.models import Bills, Payments, TransientPayment
from tenants.models import Tenant
from dateutil.relativedelta import relativedelta


# Create your views here.

@user_passes_test(lambda u: u.is_staff)
def utility_bill(request):
    rooms = Room.objects.filter(owner=request.user)
    bills = Bills.objects.filter(room__owner=request.user)

    form_room = Room.objects.filter(owner=request.user, is_archive=False)

    if request.method == "POST":
        if "button" in request.POST:
            if request.POST.get("button") == "add_utility":
                form = BillsForm(request.POST)
                if form.is_valid():
                    form = form.save(commit=False)
                    form.room = Room.objects.get(id=request.POST.get('room'))
                    form.save()
                    messages.success(request, 'Utility bill added successfully')
                    return redirect('utility-bill')
                else:
                    messages.error(request, 'Error adding utility bill')
                    return redirect('utility-bill')
            elif request.POST.get("button") == "delete_utility":
                try:
                    bill = Bills.objects.get(id=request.POST.get('id_delete'))
                    bill.delete()
                    messages.success(request, 'Utility bill deleted successfully')
                    return redirect('utility-bill')
                except:
                    messages.error(request, 'Error deleting utility bill')
                    return redirect('utility-bill')
            elif request.POST.get("button") == "edit_utility":
                try:
                    print("request.POST.get('id_bills'", request.POST.get('id_bills'))
                    room = Room.objects.get(id=request.POST.get('edit_room'))
                    bill = Bills.objects.get(id=request.POST.get('edit_id'))
                    bill.room = room
                    bill.bills = request.POST.get('bills')
                    bill.rate = request.POST.get('edit_rate')
                    bill.save()
                    messages.success(request, 'Utility bill edited successfully')
                    return redirect('utility-bill')
                except Exception as e:
                    messages.error(request, 'Error editing utility bill')
                    print(e)
                    return redirect('utility-bill')
    else:
        form = BillsForm()

    return render(request, 'payments/utility-bill.html',{
        'rooms': rooms,
        'form': form,
        'bills': bills,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),
        'form_room': form_room,

    })


@user_passes_test(lambda u: not u.is_superuser)
def payments(request):
    if request.user.is_superuser or request.user.is_staff:
        payments = Payments.objects.filter(room__owner=request.user)
    else:
        try:
            tenant = Tenant.objects.get(name__id=request.user.id)
            payments = Payments.objects.filter(tenant=tenant)
        except:
            tenant = None
            payments = None
    form_tenant = Tenant.objects.filter(owner=request.user, is_archive=False)
    form_room = Room.objects.filter(owner=request.user, is_archive=False)

    if request.method == "POST":
        if "button" in request.POST:
            if request.POST.get("button") == 'add_payment':

                form = PaymentsForm(request.POST)
                if form.is_valid():
                    form = form.save(commit=False)
                    form.tenant = Tenant.objects.get(id=request.POST.get('tenant'))
                    form.room = Tenant.objects.get(id=request.POST.get('tenant')).room
                    form.save()
                    messages.success(request, 'Payment added successfully')
                    return redirect('payments')
                else:
                    messages.error(request, 'Error adding payment')
                    return redirect('payments')
            elif request.POST.get("button") == 'delete_payment':
                try:
                    payment = Payments.objects.get(id=request.POST.get('id_delete'))
                    payment.delete()
                    messages.success(request, 'Payment deleted successfully')
                    return redirect('payments')
                except:
                    messages.error(request, 'Error deleting payment')
                    return redirect('payments')
    else:
        form = PaymentsForm()


    return render(request, 'payments/payments.html',{
        'payments': payments,
        'form': form,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),
        'form_tenant': form_tenant,
        'form_room': form_room,

    })

@user_passes_test(lambda u: not u.is_superuser)
def payments_info(request, id):
    payment = Payments.objects.get(id=id)

    form = PaymentsForm(instance=payment)

    if request.method == "POST":
        form = PaymentsForm(request.POST, instance=payment)
        if form.is_valid():
            form.save()
            messages.success(request, 'Payment edited successfully')
            return redirect('payments')
        else:
            messages.error(request, 'Error editing payment')
            return redirect('payments')



    return render(request, 'payments/payments-info.html',{
        'payment': payment,
        'form': form,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),

    })

@user_passes_test(lambda u: u.is_staff)
def income(request):


    """
    [
        {
            month: 'January',
            income: 10000,
        },
        {
            month: 'February',
            income: 10000,
        }

    ]
    """
    # create a list of dictionaries of names of the months and income
    # get all the months of payments
    payments = Payments.objects.filter(room__owner=request.user)
    transient_payments = TransientPayment.objects.filter(room__owner=request.user)
    months = []
    for payment in payments:
        total_amount = 0
        tempdict = {}
        if not any(payment.date.strftime('%B') in d['month'] for d in months):

            tempdict["month"] = payment.date.strftime('%B')
            months.append(tempdict)
        else:
            pass

    # get the total amount of payments per month
    for month in months:
        total_amount = 0
        for payment in payments:
            if month["month"] == payment.date.strftime('%B'):
                total_amount += float(payment.amount)
        month["income"] = total_amount

    # get the total amount of transient payments per month
    for month in months:
        total_amount = 0
        for transient_payment in transient_payments:
            if month["month"] == transient_payment.date.strftime('%B'):
                total_amount += float(transient_payment.amount)
        month["income"] += total_amount








    return render(request, 'payments/income.html',{
        # 'income_list': income_list,
        'months': months,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),

    })

@user_passes_test(lambda u: u.is_staff)
def collectibles(request):
    #########################
    tenants = Tenant.objects.filter(owner=request.user)
    print("tenants", tenants)
    for tenant in tenants:
        if tenant.add_month is not None:
            if tenant.add_month < datetime.now().date():
                print("add month is less than now")
                print("late")
                tenant.previous_balance += tenant.current_balance
                tenant.current_balance = 0

                tenant.add_month = tenant.add_month + timedelta(days=30)

                tenant.save()
            else:
                print("add month is greater than now")
                print("not late")
                # get all payments
                payments = Payments.objects.filter(tenant=tenant)
                print(payments)
                total = 0
                print(total)
                for payment in payments:
                    total += float(payment.amount)
                tenant.amount_paid = total
                tenant.save()


    #########################
    tenants = Tenant.objects.filter(room__isnull=False, owner=request.user)

    collectibles_lists = []

    for tenant in tenants:
        bills = Bills.objects.filter(room=tenant.room)
        total_bills = 0
        if bills:
            for bill in bills:
                total_bills += float(bill.rate)

        total_due = 0
        try:
            total_due = float(tenant.previous_balance) + float(total_bills)
        except:
            pass

        amount_paid = 0
        try:
            for payment in Payments.objects.filter(tenant=tenant):
                amount_paid += float(payment.amount)
        except:
            pass

        current_balance = 0
        try:
            current_balance = float(total_due) - float(tenant.amount_paid)
            tenant.current_balance = current_balance
            tenant.save()
        except Exception as e:
            print("error")
            print(e)




        collectibles_lists.append({
            'tenant': tenant,
            'room': tenant.room.name,
            'monthly_due': total_bills,
            'previous_balance': tenant.previous_balance,

templates/payments/payments.html
{% extends 'base/base.html' %}

{% block page-title %}
    Payments
{% endblock %}

{% block style %}

{% endblock %}

{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("payments").className += " active";
    </script>
    <script>
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.delete', function () {
            var id = $(this).closest('tr').find('td:nth-child(1)').text();
            $('#id_delete').val(id);
        });
    </script>
{% endblock %}




{% block modal %}
    {% if request.user.is_superuser or request.user.is_staff %}
        <div class="col-sm-6">
            <div class="float-sm-right">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#addPayment">
                    Add Payments
                </button>
            </div>
        </div>
    {% endif %}
{% endblock %}




{% block content %}

    <section class="content">
        <div class="container-fluid">


            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}



            <div class="card card-info elevation-2">
                <br>
                <div class="col-md-12 table-responsive">
                    <table id="example1" class="table table-bordered table-hover">
                        <thead class="btn-cancel">
                        <tr>
                            <th hidden>ID</th>
                            <th>Date</th>
                            <th>Tenant</th>
                            <th>Room</th>
                            <th>Amount</th>
                            <th>Note</th>
                            <th>Actions</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for payment in payments %}
                            <tr>
                                <td hidden>{{ payment.id }}</td>
                                <td>{{ payment.date }}</td>
                                <td>{{ payment.tenant }}</td>
                                <td>{{ payment.room }}</td>
                                <td>{{ payment.amount|floatformat:2 }}</td>
                                <td>{{ payment.note }}</td>

                                <td class="text-right">
                                    <a type="button" class="btn btn-sm btn-primary"
                                       href="{% url 'payments-info' payment.id %}"><i class="fa fa-eye"></i></a>
                                    {% if request.user.is_superuser or request.user.is_staff %}
                                    <a class="btn btn-sm btn-danger delete" href="#" data-bs-toggle="modal"
                                       data-bs-target="#deletePayment"><i
                                            class="fa fa-trash-alt"></i></a>
                                    {% endif %}
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal -->
    <div class="modal fade" id="addPayment" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Payments</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="id_tenant" class="form-label">Tenant</label>
                        <select name="tenant" class="form-control" required="" id="id_tenant">
                            <option value="" selected="">---------</option>
                            {% for tenant in form_tenant %}
                            	<option value="{{ tenant.id }}">{{ tenant.name.get_full_name }}</option>
                            {% endfor %}



                        </select>
                        {{ form }}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="add_payment">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="modal fade" id="deletePayment" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Payment</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to delete this payment?</p>
                        <input type="text" id="id_delete" name="id_delete" hidden>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="delete_payment">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/payments/utility-bill.html
{% extends 'base/base.html' %}

{% block page-title %}
    Utility Bills
{% endblock %}

{% block style %}

{% endblock %}

{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("nav-utility-bills").className += " active";
    </script>

    <script>
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.edit', function () {
            var room = $(this).closest('tr').find('td:nth-child(1)').text();
            var bills = $(this).closest('tr').find('td:nth-child(3)').text();
            var rate = $(this).closest('tr').find('td:nth-child(4)').text();
            var id = $(this).closest('tr').find('td:nth-child(5)').text();
            console.log(room);
            console.log(bills);
            console.log(rate);
            $('#edit_room').val(room);
            $('#edit_bills').val(bills);
            $('#edit_rate').val(rate);
            $('#edit_id').val(id);

        });
        $(document).on('click', '.delete', function () {
            var id = $(this).closest('tr').find('td:nth-child(5)').text();
            $('#id_delete').val(id);

        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Get the select element
            var selectElement = document.getElementById('id_bills');

            // Find the option with value="Rent"
            var optionToRemove = selectElement.querySelector('option[value="Rent"]');

            // Remove the option if it exists
            if (optionToRemove) {
                optionToRemove.remove();
            }
        });
    </script>
    <script>

        // Get all table rows except the header row
        const rows = document.querySelectorAll("#example1 tbody tr");

        // Loop through each row
        rows.forEach(row => {
            const billType = row.cells[2].textContent.trim(); // Assuming "Bills" column is at index 2

            // Check if the bill type is "Rent"
            if (billType === "Rent") {
                const deleteButton = row.querySelector(".delete");
                if (deleteButton) {
                    deleteButton.remove(); // Remove the delete button
                }
                const editButton = row.querySelector(".edit");
                if (editButton) {
                    editButton.remove(); // Remove the delete button
                }
            }
        });
    </script>
{% endblock %}


{% block modal %}
    <div class="col-sm-6">
        <div class="float-sm-right">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#addUtilityBills">
                Add Utility Bills
            </button>
        </div>
    </div>
{% endblock %}



{% block content %}

    <section class="content">
        <div class="container-fluid">


            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}



            <div class="card card-info elevation-2">
                <br>
                <div class="col-md-12 table-responsive">
                    <table id="example1" class="table table-bordered table-hover">
                        <thead class="btn-cancel">
                        <tr>
                            <th>Room ID</th>
                            <th>Room</th>
                            <th>Bills</th>
                            <th>Rate</th>
                            <th hidden>Utility ID</th>
                            <th>Actions</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for bill in bills %}
                            <tr>
                                <td>{{ bill.id }}</td>
                                <td>{{ bill.room }}</td>
                                <td>{{ bill.bills }}</td>
                                <td>{{ bill.rate|floatformat:2 }}</td>
                                <td hidden>{{ bill.id }}</td>

                                <td class="text-right">
                                    <button type="button" class="btn btn-sm btn-warning edit" data-bs-toggle="modal"
                                            data-bs-target="#editUtilityBills"><i class="fa fa-edit"></i></button>
                                    <a class="btn btn-sm btn-danger delete" href="#" data-bs-toggle="modal"
                                       data-bs-target="#deleteUtilityBill"><i
                                            class="fa fa-trash-alt"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal -->
    <div class="modal fade" id="addUtilityBills" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Utility Bills</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="id_room" class="form-label">Room</label>
                        <select name="room" class="form-control" required="" id="id_room">
                            <option value="" selected="">---------</option>
                            {% for room in form_room %}
                                <option value="{{ room.id }}">{{ room.name }}</option>
                            {% endfor %}
                        </select>
                        {{ form }}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="add_utility">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="modal fade" id="editUtilityBills" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Utility Bills</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <input type="text" name="edit_id" class="form-control" maxlength="100" id="edit_id" >
                        <label for="id_room">Room:</label>
                        <select name="edit_room" class="form-control" required="" id="edit_room">
                            <option value="" selected="">---------</option>
                            {% for room in form_room %}
                                <option value="{{ room.id }}">{{ room.name }}</option>
                            {% endfor %}
                        </select>
                        <label for="id_bills">Bills:</label>
                        <select name="bills" class="form-control" maxlength="100" id="id_bills">
                            <option value="Electricity">Electricity</option>

                            <option value="Water">Water</option>

                            <option value="Internet">Internet</option>

                            <option value="Cable">Cables</option>

                            <option value="Others">Others</option>

                        </select>
                        <label for="id_rate">Rate:</label>
                        <input type="text" name="edit_rate" class="form-control" maxlength="100" required=""
                               id="edit_rate">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="edit_utility">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteUtilityBill" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Utility Bills</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to delete this utility bill?</p>

                        <input type="text" id="id_delete" name="id_delete" hidden>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="delete_utility">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}