boardinghouse/urls.py
from django.urls import path

from boardinghouse import views

urlpatterns = [
    path('boardinghouse/', views.boardinghouse, name='boardinghouse'),
    path('boardinghouse/archive/', views.boardinghouse_archive, name='boardinghouse_archive'),
    path('boardinghouse/<int:id>/', views.boardinghouse_detail, name='boardinghouse_detail'),
    path('boardinghouse/delete_image/<int:id>', views.delete_image, name='delete_image'),
    path('rooms/', views.rooms, name='rooms'),
    path('rooms/archive/', views.rooms_archive, name='rooms_archive'),
    path('rooms/<int:id>/', views.rooms_detail, name='room_detail'),
    path('rooms/manage/', views.manage_rooms, name='manage_rooms'),
    path('rooms/manage/<int:id>/', views.manage_rooms_detail, name='manage_rooms_detail'),
    path('beds/', views.beds, name='beds'),
    path('beds_assignment/', views.beds_assignment, name='beds_assignment'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('homepage.urls')),
    path('', include('tenants.urls')),
    path('', include('boardinghouse.urls')),
    path('', include('payments.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardinghouse/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from payments.models import Bills


# Create your models here.

class BoardingHouse(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    address = models.CharField(max_length=100)
    num_beds = models.IntegerField()
    num_baths = models.IntegerField()
    latitude = models.DecimalField(max_digits=25, decimal_places=20)
    longitude = models.DecimalField(max_digits=25, decimal_places=20)
    image = models.ImageField(upload_to='boardinghouse', blank=True)
    owner = models.ForeignKey('auth.User', related_name='boardinghouses', on_delete=models.CASCADE)
    is_archive = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class BoardingHouseImage(models.Model):
    boardinghouse = models.ForeignKey(BoardingHouse, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='boardinghouse', blank=True)

    def __str__(self):
        return self.boardinghouse.name



class Room(models.Model):
    boardinghouse = models.ForeignKey(BoardingHouse, related_name='rooms', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    num_bed = models.IntegerField()

    male_female_choices = (
        ("For Male Only", "For Male Only"),
        ("For Female Only", "For Female Only"),
        ("For Both Male and Female", "For Both Male and Female")
    )
    male_female = models.CharField(choices=male_female_choices, max_length=50)
    vacant = models.BooleanField(default=True)
    image = models.ImageField(upload_to='room', blank=True)
    owner = models.ForeignKey('auth.User', related_name='rooms', on_delete=models.CASCADE)
    is_archive = models.BooleanField(default=False)


    def __str__(self):
        return self.name




@receiver(post_save, sender=Room)
def update_bills(sender, instance, created, **kwargs):
    # check if room is in Bills
    bills = Bills.objects.filter(room=instance)
    if bills:
        for bill in bills:
            bill.rate = instance.price
            bill.save()
    else:
        Bills.objects.create(
            room=instance,
            bills="Rent",
            rate=instance.price
        )

tenants/models.py
from datetime import timedelta, datetime

from dateutil.relativedelta import relativedelta
from django.db import models

# Create your models here.
class Tenant(models.Model):
    name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='owner', null=True, blank=True)
    room = models.ForeignKey('boardinghouse.Room', on_delete=models.CASCADE, null=True, blank=True)
    date_start = models.DateField(null=True, blank=True)
    add_month = models.DateField(null=True, blank=True)
    current_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    previous_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    address = models.CharField(max_length=100, null=True, blank=True)
    contact_number = models.CharField(max_length=20, null=True, blank=True)
    is_archive = models.BooleanField(default=False)

    def __str__(self):
        return self.name.get_full_name()

    def save(self, *args, **kwargs):
        if self.date_start != None and self.add_month == None:
            date_start = str(self.date_start)
            date_start = date_start.split('-')
            date_start = datetime(int(date_start[0]), int(date_start[1]), int(date_start[2]))
            self.add_month = date_start + relativedelta(months=1)
        super(Tenant, self).save(*args, **kwargs)

boardinghouse/forms.py
from django import forms

from boardinghouse.models import BoardingHouse, Room
from tenants.models import Tenant


class BoardingHouseForms(forms.ModelForm):
    class Meta:
        model = BoardingHouse
        fields = ('name', 'description', 'address', 'num_beds', 'num_baths', 'latitude', 'longitude', 'image')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'num_beds': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'num_baths': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'longitude': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'required': 'true'}),
        }


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('boardinghouse', 'name', 'price', 'num_bed', 'male_female', 'vacant', 'image')
        widgets = {
            'boardinghouse': forms.Select(attrs={'class': 'form-control', 'required': 'true'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'num_bed': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'male_female': forms.Select(attrs={'class': 'form-control', 'required': 'true'}),
            'vacant': forms.NumberInput(attrs={'class': 'form-control' }),
            'image': forms.FileInput(attrs={'class': 'form-control', 'required': 'true'}),
        }

boardinghouse/views.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

from homepage.models import Feedback, Notice
from tenants.models import Tenant
from .forms import BoardingHouseForms, RoomForm
from .models import BoardingHouse, Room, BoardingHouseImage


# Create your views here.

@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def boardinghouse(request):
    if request.user.is_superuser:
        boardinghouses = BoardingHouse.objects.filter(is_archive=False)
    else:
        boardinghouses = BoardingHouse.objects.filter(owner=request.user, is_archive=False)

    if request.method == 'POST':
        forms = BoardingHouseForms(request.POST, request.FILES)
        print("button" in request.POST)

        if "button" in request.POST:
            print(request.POST.get('button'))
            if request.POST.get('button') == 'add_bhouse':
                try:
                    if forms.is_valid():
                        boardinghouse = forms.save(commit=False)
                        boardinghouse.owner = request.user
                        boardinghouse.save()
                        if request.FILES.get('more_image'):
                            for image in request.FILES.getlist('more_image'):
                                BoardingHouseImage.objects.create(boardinghouse=boardinghouse, image=image)
                        messages.success(request, 'Boarding House has been added successfully')
                        print('Boarding House has been added successfully')
                        return redirect('boardinghouse')
                    else:
                        messages.error(request, 'Error adding boarding house')
                        print('Error adding boarding house', forms.errors)
                        return redirect('boardinghouse')
                except Exception as e:
                    messages.error(request, 'Error adding boarding house')
                    print('Error adding boarding house', e)
                    return redirect('boardinghouse')

            elif request.POST.get('button') == 'delete_bhouse':
                try:
                    id = request.POST.get('delete_id')
                    boardinghouse = get_object_or_404(BoardingHouse, id=id, owner=request.user)
                    boardinghouse.is_archive = True
                    boardinghouse.save()
                    # get all rooms of boarding house
                    rooms = Room.objects.filter(boardinghouse=boardinghouse)
                    for r in rooms:
                        r.is_archive = True
                        r.save()
                        # get all tenants of boarding house
                        tenants = Tenant.objects.filter(room=r)
                        for t in tenants:
                            t.is_archive = True
                            t.save()
                    # get all tenants of boarding house
                    messages.success(request, 'Boarding House has been deleted successfully')
                    print('Boarding House has been deleted successfully')
                    return redirect('boardinghouse')
                except Exception as e:
                    messages.error(request, 'Error deleting boarding house')
                    print('Error deleting boarding house', e)
                    return redirect('boardinghouse')
    else:
        forms = BoardingHouseForms()

    return render(request, 'boardinghouse/boardinghouse.html', {
        'form': forms,
        'boardinghouses': boardinghouses,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),

    })


@user_passes_test(lambda u: u.is_superuser)
def boardinghouse_archive(request):
    boardinghouses = BoardingHouse.objects.filter(is_archive=True)

    if request.method == "POST":
        if request.POST.get("button") == "restore":
            try:
                id = request.POST.get('restore_id')
                boardinghouse = get_object_or_404(BoardingHouse, id=id)
                boardinghouse.is_archive = False
                boardinghouse.save()
                rooms = Room.objects.filter(boardinghouse=boardinghouse)
                for r in rooms:
                    r.is_archive = False
                    r.save()
                    # get all tenants of boarding house
                    tenants = Tenant.objects.filter(room=r)
                    for t in tenants:
                        t.is_archive = False
                        t.save()
                messages.success(request, 'Boarding House has been restored successfully')
                print('Boarding House has been restored successfully')
                return redirect('boardinghouse_archive')
            except Exception as e:
                messages.error(request, 'Error restoring boarding house')
                print('Error restoring boarding house', e)
                return redirect('boardinghouse_archive')
        elif request.POST.get("button") == "delete":
            try:
                id = request.POST.get('delete_id')
                boardinghouse = get_object_or_404(BoardingHouse, id=id)
                boardinghouse.delete()
                messages.success(request, 'Boarding House has been deleted successfully')
                print('Boarding House has been deleted successfully')
                return redirect('boardinghouse_archive')
            except Exception as e:
                messages.error(request, 'Error deleting boarding house')
                print('Error deleting boarding house', e)
                return redirect('boardinghouse_archive')

    return render(request, 'boardinghouse/boardinghouse_archive.html', {
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),
        'boardinghouses': boardinghouses,
    })


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def boardinghouse_detail(request, id):
    boardinghouse = get_object_or_404(BoardingHouse, id=id)
    boardinghouse_images = BoardingHouseImage.objects.filter(boardinghouse=boardinghouse)
    form = BoardingHouseForms(instance=boardinghouse)
    if request.method == "POST":
        form = BoardingHouseForms(request.POST, request.FILES, instance=boardinghouse)
        if form.is_valid():
            form.save()
            if request.FILES.get('more_image'):
                for image in request.FILES.getlist('more_image'):
                    BoardingHouseImage.objects.create(boardinghouse=boardinghouse, image=image)
            messages.success(request, 'Boarding House has been updated successfully')
            print('Boarding House has been updated successfully')
            return redirect('boardinghouse')
        else:
            messages.error(request, 'Error updating boarding house')
            print('Error updating boarding house', form.errors)
            return redirect('boardinghouse')

    return render(request, 'boardinghouse/boardinghouse_detail.html', {
        'boardinghouse': boardinghouse,
        'form': form,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'notice': Notice.objects.filter(is_viewed=False).count(),
        'boardinghouse_images': boardinghouse_images,

    })


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def delete_image(request, id):
    image = get_object_or_404(BoardingHouseImage, id=id)
    image.delete()
    messages.success(request, 'Image has been deleted successfully')
    print('Image has been deleted successfully')
    return redirect('boardinghouse_detail', id=image.boardinghouse.id)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def rooms(request):
    if request.user.is_superuser:
        rooms = Room.objects.filter(is_archive=False)
    else:
        rooms = Room.objects.filter(owner=request.user, is_archive=False)
    bhouses = BoardingHouse.objects.filter(owner=request.user, is_archive=False)
    if request.method == "POST":
        forms = RoomForm(request.POST, request.FILES)
        if "button" in request.POST:
            if request.POST.get("button") == "add_room":
                if forms.is_valid():
                    room = forms.save(commit=False)
                    room.owner = request.user
                    room.boardinghouse = BoardingHouse.objects.get(id=request.POST.get('boardinghouse'))
                    room.save()
                    messages.success(request, 'Room has been added successfully')
                    print('Room has been added successfully')
                    return redirect('rooms')
                else:
                    messages.error(request, 'Error adding room')
                    print('Error adding room', forms.errors)
                    return redirect('rooms')
            elif request.POST.get("button") == "delete_room":
                try:
                    id = request.POST.get('delete_id')
                    room = get_object_or_404(Room, id=id)
                    room.is_archive = True
                    room.save()
                    tenants = Tenant.objects.filter(room=room)
                    for t in tenants:
                        t.is_archive = True
                        t.save()
                    messages.success(request, 'Room has been deleted successfully')
                    print('Room has been deleted successfully')
                    return redirect('rooms')
                except Exception as e:
                    messages.error(request, 'Error deleting room')
                    print('Error room', e)
                    return redirect('rooms')

templates/boardinghouse/manage_rooms.html
{% extends 'base/base.html' %}
{% block page-title %}
    Room Management
{% endblock %}


{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("nav-room-management").className += " active";
    </script>
    <script>
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.edit', function () {
            var name = $(this).closest('tr').find('td:nth-child(2)').text();
            var room = $(this).closest('tr').find('td:nth-child(4)').text();
            var date = $(this).closest('tr').find('td:nth-child(5)').text();
            console.log(date);

            var newdate = new Date(date);
            {#format newdate to mm/dd/yyyy#}
            var formatteddate = newdate.toLocaleDateString('en-GB', {
                day: 'numeric', month: 'short', year: 'numeric'
            }).replace(/ /g, '-');


            $('#edit_name').val(name);
            $('#edit_room').val(room);
            $('.edit_date').val(formatteddate);

        });
        $(document).on('click', '.delete', function () {
            var id = $(this).closest('tr').find('td:nth-child(1)').text();
            $('#id_delete').val(id);

        });
    </script>
{% endblock %}


{% block modal %}
        {% if not request.user.is_superuser %}

    <div class="col-sm-6">
        <div class="float-sm-right">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#asignRoom">
                Assign Rooms
            </button>
        </div>
    </div>
        {% endif %}
{% endblock %}


{% block content %}

    <section class="content">
        <div class="container-fluid">


            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}



            <div class="card card-info elevation-2">
                <br>
                <div class="col-md-12 table-responsive">
                    <table id="example1" class="table table-bordered table-hover">
                        <thead class="btn-cancel">
                        <tr>
                            <th>ID</th>

                            <th>Tenant Name</th>
                            <th>Boarding House</th>
                            <th>Room ID</th>
                            <th>Room Number</th>
                            <th>Date Started</th>
                            {% if request.user.is_superuser %}
                            	<th>Owner</th>
                            {% endif %}
                            <th>Actions</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for tenant in tenants %}



                            <tr>
                                <td>{{ tenant.id }}</td>
                                <td>{{ tenant.name }}</td>
                                <td>{{ tenant.room.boardinghouse.name }}</td>
                                <td>{{ tenant.room.id }}</td>
                                <td>{{ tenant.room }}</td>
                                <td>{{ tenant.date_start }}</td>
                                {% if request.user.is_superuser %}
                                	<td>{{ tenant.room.boardinghouse.owner.get_full_name }}</td>
                                {% endif %}

                                <td class="text-right">
                                    <button type="button" class="btn btn-sm btn-success edit" data-bs-toggle="modal"
                                            data-bs-target="#edit">
                                        <i
                                                class="fa fa-eye"></i>
                                    </button>
                                    <button type="button" class="btn btn-sm btn-danger delete" data-bs-toggle="modal"
                                            data-bs-target="#delete">
                                        <i
                                                class="fa fa-trash-alt"></i>
                                    </button>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal -->

    <div class="modal fade" id="asignRoom" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Assign Room</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">

                        <label for="id_name">Name:</label>
                        <select name="name" class="form-control" required="" id="id_name">
                            <option value="" selected="" disabled>---------</option>
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.name.get_full_name }}</option>
                            {% endfor %}
                        </select>


                        <label for="id_room">Room:</label>
                        <select name="room" class="form-control" required="true" id="id_room">
                            <option value="" selected="" disabled>---------</option>
                            {% for room in rooms %}
                                <option value="{{ room.id }}">{{ room }}</option>
                            {% endfor %}


                        </select>


                        <label for="id_date_start">Date start:</label>


                        <input type="date" name="date_start" class="form-control" required="" id="id_date_start">


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="add_assignment">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


     <div class="modal fade" id="edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Assignment</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">

                        <label for="id_name">Name:</label>
                        <select name="name" class="form-control" required="" id="edit_name">
                            <option value="" selected="" disabled>---------</option>
                            {% for user in tenants %}
                                <option value="{{ user.name.username }}">{{ user.name.get_full_name }}</option>
                            {% endfor %}
                        </select>


                        <label for="id_room">Room:</label>
                        <select name="room" class="form-control" required="true" id="edit_room">
                            <option value="" selected="" disabled>---------</option>
                            {% for room in rooms %}
                                <option value="{{ room.id }}">{{ room.name }}</option>
                            {% endfor %}


                        </select>


                        <label for="id_date_start">Date start:</label>


                        <input type="date" name="date_start" class="form-control" required="" id="edit_date">


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="edit_assignment">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


     <div class="modal fade" id="delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Assignment</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">

                        <p>Are you sure you want to delete this assignment? </p>
                        <input type="text" id="id_delete" name="id_delete" hidden>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="delete_assignment">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/boardinghouse/rooms_detail.html
{% extends 'base/base.html' %}

{% block page-title %}
    {{ room.boardinghouse.name }} - {{ room.name }}
{% endblock %}

{% block style %}
    <style>
        #map {
            height: 300px;
        }
    </style>
{% endblock %}

{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("nav-room-listings").className += " active";
    </script>
    <script>
        const idImageInput = document.getElementById('id_image');

        // Remove the 'required' attribute
        idImageInput.removeAttribute('required');
    </script>
{% endblock %}

{% block modal %}

{% endblock %}

{% block content %}

    <section class="content">
        <div class="container-fluid">


            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}



            <div class="card card-info elevation-2">
                <br>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-12">
                                <label for="id_name">Boarding House: </label>
                                <select name="boardinghouse" class="form-control" required="" id="id_boardinghouse">
                                    <option value="" selected="">---------</option>
                                    {% for bhouse in bhouses %}

                                        {% if bhouse.id == room.boardinghouse.id %}
                                            <option selected value="{{ bhouse.id }}">{{ bhouse.name }}</option>
                                        {% else %}

                                            <option value="{{ bhouse.id }}">{{ bhouse.name }} </option>
                                        {% endif %}



                                    {% endfor %}

                                </select>
                            </div>

                            <div class="col-6">
                                <label for="id_name">Room Name: </label>
                                {{ form.name }}
                            </div>
                            <div class="col-6">
                                <label for="id_name">Rent price: </label>
                                {{ form.price }}
                            </div>

                            <div class="col-6">
                                <label for="id_name">Number of Bed: </label>
                                {{ form.num_bed }}
                            </div>

                            <div class="col-6">
                                <label for="id_name">Vacant: </label>
                                {{ form.vacant }}
                            </div>

                            <div class="col-12">
                                <label for="id_name">Male/Female: </label>
                                {{ form.male_female }}
                            </div>
                            <div class="col-12">
                                <label for="id_name">Image: </label>
                                {{ form.image }}
                            </div>
                        </div>
                        <div class="text-center align-content-center">
                            {% if not request.user.is_superuser %}
                                <button type="submit" class="btn btn-primary" name="button" value="add_bhouse">Save
                                    changes
                                </button>
                            {% endif %}
                            <a class="btn btn-secondary" href="{% url 'rooms' %}"> Back to Rooms
                            </a>
                        </div>
                        <br>
                    </div>
                </form>
            </div>
        </div>
    </section>

{% endblock %}