core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('homepage.urls')),
    path('', include('tenants.urls')),
    path('', include('boardinghouse.urls')),
    path('', include('payments.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenants/urls.py
from django.urls import path

from tenants import views

urlpatterns = [
    path('tenants/', views.tenants_profile, name='tenants_profile'),
    path('tenants/archive/', views.tenant_archive, name='tenant_archive'),
]

tenants/models.py
from datetime import timedelta, datetime

from dateutil.relativedelta import relativedelta
from django.db import models

# Create your models here.
class Tenant(models.Model):
    name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='owner', null=True, blank=True)
    room = models.ForeignKey('boardinghouse.Room', on_delete=models.CASCADE, null=True, blank=True)
    date_start = models.DateField(null=True, blank=True)
    add_month = models.DateField(null=True, blank=True)
    current_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    previous_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    address = models.CharField(max_length=100, null=True, blank=True)
    contact_number = models.CharField(max_length=20, null=True, blank=True)
    is_archive = models.BooleanField(default=False)

    def __str__(self):
        return self.name.get_full_name()

    def save(self, *args, **kwargs):
        if self.date_start != None and self.add_month == None:
            date_start = str(self.date_start)
            date_start = date_start.split('-')
            date_start = datetime(int(date_start[0]), int(date_start[1]), int(date_start[2]))
            self.add_month = date_start + relativedelta(months=1)
        super(Tenant, self).save(*args, **kwargs)

tenants/views.py
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from homepage.models import Feedback
from .models import Tenant

# Create your views here.


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def tenants_profile(request):
    users = User.objects.filter(tenant__isnull=True).exclude(is_superuser=True).exclude(is_staff=True)
    if request.user.is_superuser:
        tenants = Tenant.objects.filter(is_archive=False)
    else:
        tenants = Tenant.objects.filter(owner=request.user, is_archive=False)
    if request.method == "POST":
        if request.POST.get("button") == "add":
            try:
                name = request.POST.get('user')
                user_instance = User.objects.get(id=name)
                # create tenant object
                tenant = Tenant(name=user_instance)
                tenant.owner = request.user
                tenant.address = request.POST.get('address')
                tenant.contact_number = request.POST.get('number')
                tenant.save()
                messages.success(request, 'Tenant added successfully!')
                return redirect('tenants_profile')
            except Exception as e:
                print(e)
                messages.error(request, e)
                return redirect('tenants_profile')
        elif request.POST.get("button") == "archive":
            try:
                tenant = Tenant.objects.get(id=request.POST.get('delete_id'))
                tenant.is_archive = True
                tenant.save()
                messages.success(request, 'Tenant archived successfully!')
                return redirect('tenants_profile')
            except Exception as e:
                print(e)
                messages.error(request, e)
                return redirect('tenants_profile')





    return render(request, 'tenants/tenants_profile.html',{
        'users': users,
        'tenants': tenants,
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),

    })

@user_passes_test(lambda u: u.is_superuser)
def tenant_archive(request):
    tenants = Tenant.objects.filter(is_archive=True)

    if request.method == "POST":
        if request.POST.get("button") == "restore":
            try:
                tenant = Tenant.objects.get(id=request.POST.get('restore_id'))
                tenant.is_archive = False
                tenant.save()
                messages.success(request, 'Tenant restored successfully!')
                return redirect('tenants_profile')
            except Exception as e:
                print(e)
                messages.error(request, e)
                return redirect('tenants_profile')
        elif request.POST.get("button") == "delete":
            try:
                tenant = Tenant.objects.get(id=request.POST.get('delete_id'))
                tenant.delete()
                messages.success(request, 'Tenant deleted successfully!')
                return redirect('tenants_profile')
            except Exception as e:
                print(e)
                messages.error(request, e)
                return redirect('tenants_profile')

    return render(request, 'tenants/tenant_archive.html',{
        'feedback': Feedback.objects.filter(is_viewed=False, feedback_to=request.user).count(),
        'tenants': tenants,
    })

templates/tenants/tenant_archive.html
{% extends 'base/base.html' %}

{% block page-title %}
    Tenants Archive
{% endblock %}

{% block style %}

{% endblock %}

{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("nav-tenants").className += " active";
    </script>
    <script>
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.delete', function () {
            var id = $(this).closest('tr').find('td:nth-child(1)').text();
            $('#delete_id').val(id);
        });
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.restore', function () {
            var id = $(this).closest('tr').find('td:nth-child(1)').text();
            $('#restore_id').val(id);
        });
    </script>
{% endblock %}




{% block content %}

    <section class="content">
        <div class="container-fluid">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}

            <div class="card card-info elevation-2">
                <br>
                <div class="col-md-12 table-responsive">
                    <table id="example1" class="table table-bordered table-hover">
                        <thead class="btn-cancel">
                        <tr>
                            <th hidden>ID</th>
                            <th>Tenant Name</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for tenant in tenants %}



                            <tr>
                                <td hidden>{{ tenant.id }}</td>
                                <td>{{ tenant.name.get_full_name }}</td>
                                <td>{{ tenant.name.email }}</td>
                                <td class="text-right">
                                    <button type="button" class="btn btn-sm btn-success restore"
                                            data-bs-toggle="modal"
                                            data-bs-target="#restore"><i
                                            class="fa fa-recycle"></i></button>
                                    <button type="button" class="btn btn-sm btn-danger delete"
                                            data-bs-toggle="modal"
                                            data-bs-target="#delete"><i
                                            class="fa fa-trash-alt"></i></button>


                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                    <div class="text-right pb-3">
                        <a href="{% url 'tenants_profile' %}">Back to Tenants</a>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Tenant</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                <label for="id_name">Name: </label>
                                <select class="form-select" aria-label="Default select example" required name="user">
                                    <option value="" selected disabled>Open this select menu</option>
                                    {% for user in users %}
                                        <option value="{{ user.id }}">{{ user.get_full_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="add">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Tenant</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to delete this tenant?</p>

                        <input type="text" name="delete_id" id="delete_id" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="delete">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="restore" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Restore Tenant</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to restore this tenant?</p>

                        <input type="text" name="restore_id" id="restore_id" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="restore">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/tenants/tenants_profile.html
{% extends 'base/base.html' %}

{% block page-title %}
    Tenants
{% endblock %}

{% block style %}

{% endblock %}

{% block js %}
    <script>
        // add active class to nav-dashboard
        document.getElementById("nav-tenants").className += " active";
    </script>
    <script>
        {#        when delete button in action clicked, get the username of user#}
        $(document).on('click', '.delete', function () {
            var id = $(this).closest('tr').find('td:nth-child(1)').text();
            $('#delete_id').val(id);
        });
    </script>
{% endblock %}

{% block modal %}
        {% if not request.user.is_superuser %}

    <div class="col-sm-6">
        <div class="float-sm-right">
            <button type="button" class="btn btn-primary" onclick="myFunctionModal()" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">
                Add Tenant
            </button>
        </div>
    </div>
        {% endif %}
{% endblock %}


{% block content %}

    <section class="content">
        <div class="container-fluid">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>

                {% endfor %}
            {% endif %}

            <div class="card card-info elevation-2">
                <br>
                <div class="col-md-12 table-responsive">
                    <table id="example1" class="table table-bordered table-hover">
                        <thead class="btn-cancel">
                        <tr>
                            <th hidden>ID</th>
                            <th>Tenant Name</th>
                            <th>Email</th>
                            <th>Contact Number</th>
                            <th>Address</th>
                            {% if request.user.is_superuser %}
                                <th>Owner</th>
                            {% endif %}
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for tenant in tenants %}



                            <tr>
                                <td hidden>{{ tenant.id }}</td>
                                <td>{{ tenant.name.get_full_name }}</td>
                                <td>{{ tenant.name.email }}</td>
                                <td>{{ tenant.contact_number }}</td>
                                <td>{{ tenant.address }}</td>
                                {% if request.user.is_superuser %}
                                    <td>{{ tenant.owner.get_full_name }}</td>
                                {% endif %}
                                <td class="text-right">
                                    <button type="button" class="btn btn-sm btn-danger delete"
                                            data-bs-toggle="modal"
                                            data-bs-target="#delete"><i
                                            class="fa fa-trash-alt"></i></button>

                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                    {% if request.user.is_superuser %}

                        <div class="text-right pb-3">
                            <a href="{% url 'tenant_archive' %}">View Archived Tenants</a>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </section>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Tenant</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                <label for="id_name">Name: </label>
                                <select class="form-select" aria-label="Default select example" required name="user">
                                    <option value="" selected disabled>Open this select menu</option>
                                    {% for user in users %}
                                        <option value="{{ user.id }}">{{ user.get_full_name }}</option>
                                    {% endfor %}
                                </select>
                                <label for="">Contact Number: </label>
                                <input type="text" name="number" id="id_number" required class="form-control" placeholder="09123456789" pattern="(^\+639\d{9}$)|(^\d{11}$)" title="Please enter a valid Philippine contact number in the format: +639123456789 or 09123456789">
                                <label for="">Address: </label>
                                <input type="text" name="address" id="id_address" required class="form-control">

                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="add">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Tenant</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to delete this tenant?</p>

                        <input type="text" name="delete_id" id="delete_id" hidden>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" name="button" value="archive">Save changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}